name: build-protobuf-schemas

on:
  push:
    branches:
      - "main"

jobs:
  build:
    name: build-protobufs
    runs-on: ubuntu-latest
    container:
      image: bufbuild/buf:1.12.0
    steps:
      # Checkout to release branch
      - uses: actions/checkout@v3
        with:
          ref: 'main'
          token: ${{ secrets.GIT_TOKEN }}
      
      - name: configure the git user
        run: |
          git config --global user.email "github-actions[bot]@users.noreply.github.com"
          git config --global user.name "github-actions[bot]"

      - name: ready the branch
        run: |
          git config --global --add safe.directory /__w/buf/buf
          git fetch origin release
          git checkout origin/release
          git merge --squash origin/main --allow-unrelated-histories
          
      # Runs commands using the runners shell
      # This step will call buf generate 
      - name: generate buf file
        run: |
          mkdir -p gen
          touch gen/test12.tf

      - name: Commit generated files
        run: |
          git reset
          git add -f gen/
          git commit -m "${{ github.event.head_commit.message }}" --author="github-actions[bot] <github-actions[bot]@users.noreply.github.com>"
          git push -v -u origin release --force
          
      # - name: Push generated files to release
      #   uses: ad-m/github-push-action@master
      #   with:
      #     github_token: ${{ secrets.GIT_TOKEN }}
      #     branch: release
      #     force: true
