name: build-protobuf-schemas

on:
  push:
    branches:
      - "main"
    paths:
      - '**.proto'

jobs:
  build:
    name: build-protobufs
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
        with:
          ref: 'main'
          token: ${{ secrets.GIT_TOKEN }}
      
      # - name: configure the git user
      #   run: |
      #     git config --global user.email "github-actions[bot]@users.noreply.github.com"
      #     git config --global user.name "github-actions[bot]"

      - name: ready the branch
        run: |
          git fetch origin release
          git checkout origin/release
          git merge --squash origin/main --allow-unrelated-histories
          
      - name: generate buf file
        run: |
          BIN="/usr/local/bin" && \
          VERSION="1.12.0" && \
            curl -sSL \
              "https://github.com/bufbuild/buf/releases/download/v${VERSION}/buf-$(uname -s)-$(uname -m)" \
              -o "${BIN}/buf" && \
            chmod +x "${BIN}/buf"

          buf generate
          git reset
          git add -f gen/
          git commit -m "${{ github.event.head_commit.message }}" --author="github-actions[bot] <github-actions[bot]@users.noreply.github.com>"
          
      - name: Push generated files to release
        uses: ad-m/github-push-action@master
        with:
          github_token: ${{ secrets.GIT_TOKEN }}
          branch: release
          force: true
