name: build-protobuf

on:
  pull_request:
    types:
      - "closed"
    branches:
      - "main"
    paths:
      - '**.proto'

jobs:
  build:
    name: build
    runs-on: ubuntu-latest
    if: ${{ github.event.pull_request.merged }}
    steps:
      - uses: actions/checkout@v3
        with:
          token: ${{ secrets.GIT_TOKEN }}
          fetch-depth: 2
      
      - name: configure the git user
        run: |
          git config --global user.email "github-actions[bot]@users.noreply.github.com"
          git config --global user.name "github-actions[bot]"

      # - name: ready the branch
      #   run: |
      #     git fetch origin release
      #     git checkout origin/release
      #     git merge --squash origin/main --allow-unrelated-histories
          
      - name: generate buf file
        run: |
          BIN="/usr/local/bin" && \
          VERSION="1.12.0" && \
            curl -sSL \
              "https://github.com/bufbuild/buf/releases/download/v${VERSION}/buf-$(uname -s)-$(uname -m)" \
              -o "${BIN}/buf" && \
            chmod +x "${BIN}/buf"
          buf generate

      # - name: build ruby package
      #   run: |
      #     apt-get install ruby ruby-dev
      #     gem install bundler

      # - name: build python package
      #   run: |
      #     create minimal directory structure and
      #     upload the file zip to aws codeartifact.

      - name: Commit changes
        run: |
          git add -f .
          git commit --amend --no-edit --author="github-actions[bot] <github-actions[bot]@users.noreply.github.com>"
          
      - name: Push generated files to release
        uses: ad-m/github-push-action@master
        with:
          github_token: ${{ secrets.GIT_TOKEN }}
          branch: main
          force: true
