name: lint
on:
  pull_request:
    branches:
      - "main"
    paths:
      - '**.proto'
jobs:
  lint:
    name: lint
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: bufbuild/buf-setup-action@v1.12.0
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
      - uses: bufbuild/buf-lint-action@v1
      - name: verify if compiled code is pushed
        run: |
          if [ -z "$(ls -A gen)" ]; then
            echo "Missing compiled files!"
            exit 1
          fi
      - uses: bufbuild/buf-breaking-action@v1
        with:
          against: "https://github.com/goakshit/buf.git#branch=main"
