name: tag
on:
  push: 
    branches: 
      - 'main'
    paths:
      - '**.proto'

permissions:
  actions: write
  contents: write

jobs:
  tag:
    name: tag-commit
    runs-on: ubuntu-latest
    outputs:
      tag: ${{ steps.tag_version.outputs.new_tag }}
      version: ${{ steps.tag_version.outputs.new_version }}
    steps:
      - uses: actions/checkout@v3
        with:
          ref: 'main'
      - name: bump version and push tag
        id: tag_version
        uses: mathieudutour/github-tag-action@v6.1
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          custom_release_rules: 'feat:minor,enhancement:minor,fix:patch,hotfix:patch,breaking:major,perf:major'
  
  release-ruby:
    needs: tag
    name: release-ruby
    runs-on: ubuntu-latest
    permissions:
      contents: write
      packages: write
    steps:
      - uses: actions/checkout@v3
        with:
          ref: ${{needs.tag.outputs.tag}}
      - name: create gemspec
        run: |
          cat << 'EOL' > gen/ruby/proto.gemspec
          Gem::Specification.new do |spec|
            spec.name          = "proto"
            spec.date          = Time.now.strftime('%Y-%m-%d')
            spec.version       = "${{needs.tag.outputs.version}}"
            spec.email         = ["akshitdhar@live.com"]
            spec.author        = "goakshit"
            spec.summary       = "Compiled protobuf files"

            spec.metadata['github_repo']     = "https://github.com/goakshit/buf"
            spec.metadata['source_code_uri'] = "https://github.com/goakshit/buf"

            spec.files         = Dir.chdir(File.expand_path('..', __FILE__)) do
              `git ls-files -z`.split("\x0").reject { |f| f.match(%r{^(test|spec|features)/}) }
            end
            spec.bindir        = "exe"
            spec.executables   = spec.files.grep(%r{^exe/}) { |f| File.basename(f) }
            spec.require_paths = ["lib"]
            spec.required_ruby_version = ">= 2.6.0"
          end
          EOL

          mkdir gen/ruby/lib
          mv payment/ report/ gen/ruby/lib/

          cat << 'EOL' > gen/ruby/lib/report/proto.rb
          Dir[File.expand_path(File.join(File.dirname(File.absolute_path(__FILE__)), "v1")) + "/**/*.rb"].each do |file|
            require file
          end
          EOL
          
          cat << 'EOL' > gen/ruby/lib/payment/proto.rb
          Dir[File.expand_path(File.join(File.dirname(File.absolute_path(__FILE__)), "v1")) + "/**/*.rb"].each do |file|
            require file
          end
          EOL

          git add -f gen/ruby

          sudo apt-get install -y curl gnupg build-essential
          curl -sSL https://rvm.io/pkuczynski.asc | gpg --import -
          \curl -sSL https://get.rvm.io | bash -s stable
          source ~/.rvm/scripts/rvm

          rvm install ruby-3.1.1
          rvm --default use ruby-3.1.1

          cd gen/ruby
          gem build proto.gemspec

      - name: release
        run: |
          mkdir -p ~/.gem
          touch ~/.gem/credentials
          chmod 600 ~/.gem/credentials
          echo ":github: Bearer ${{secrets.GITHUB_TOKEN}}" >> ~/.gem/credentials

          gem push --key github --host "https://rubygems.pkg.github.com/goakshit" gen/ruby/proto-${{needs.tag.outputs.version}}.gem
