name: bump version
on:
  workflow_run:
    workflows: [build protobuf schemas]
    types:
      - completed
  push:
    branches: ["release"]

jobs:
  bump_version:
    runs-on: ubuntu-latest
    if: ${{ github.event.workflow_run.conclusion == 'success' }}
    steps:
      - uses: actions/checkout@v2
        with:
          ref: 'release'
      - name: bump version and push tag
        id: tag_version
        uses: mathieudutour/github-tag-action@v6.1
        with:
          github_token: ${{ secrets.GIT_TOKEN }}
