name: tag
on:
  push: 
    branches: 
      - 'main'
    paths:
      - '**.proto'

permissions:
  actions: write
  contents: write

jobs:
  tag:
    name: tag-commit
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
        with:
          ref: 'main'
      - name: bump version and push tag
        id: tag_version
        uses: mathieudutour/github-tag-action@v6.1
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          custom_release_rules: 'feat:minor,enhancement:minor,fix:patch,hotfix:patch,breaking:major,perf:major'
