name: bump-version
on:
  workflow_run:
    workflows: [build-protobuf]
    types:
      - completed

jobs:
  bump_version:
    name: tag-release
    runs-on: ubuntu-latest
    if: ${{ github.event.workflow_run.conclusion == 'success' }}
    steps:
      - uses: actions/checkout@v3
        with:
          ref: 'main'
      - name: bump version and push tag
        id: tag_version
        uses: mathieudutour/github-tag-action@v6.1
        with:
          github_token: ${{ secrets.GIT_TOKEN }}
          default_bump: 'false'
