name: bump-version
on:
  workflow_run:
    workflows: [build-protobuf]
    types:
      - completed

jobs:
  bump_version:
    name: tag-release
    runs-on: ubuntu-latest
    if: ${{ github.event.workflow_run.conclusion == 'success' }}
    steps:
      - uses: actions/checkout@v3
        with:
          ref: 'main'
      - name: bump version and push tag
        id: tag_version
        uses: anothrNick/github-tag-action@1.61.0
        env:
          GITHUB_TOKEN: ${{ secrets.GIT_TOKEN }}
          WITH_V: true
          DEFAULT_BUMP: 'none'
